export const projects = [
  {
    id: 2,
    imageSrc: require("../../public/images/saisanjeevaniyoga-in.png"),
    title: "Sai Sanjeevani Yoga",
    description:
      "Focused on development and deployment and minimal design contribution.",
    githubLink: "https://www.saisanjeevaniyoga.in/",
    demoLink: "https://www.saisanjeevaniyoga.in/",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Side Project",
    involvement: "Development to Deployment",
  },
  {
    id: 1,
    imageSrc: require("../../public/images/flowinterio.png"),
    title: "Flow Interio",
    description:
      "Involved in design through to deployment for top interior designers in Hyderabad.",
    githubLink: "https://flowinterio.com/",
    demoLink: "https://flowinterio.com/",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Work",
    involvement: "Design to Deployment",
  },
  {
    id: 3,
    imageSrc: require("../../public/images/gzero-in.png"),
    title: "GZero",
    description:
      "Handled design to deployment for a sports booking platform in Mohali.",
    githubLink: "https://www.gzero.in/",
    demoLink: "https://www.gzero.in/",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Work",
    involvement: "Design to Deployment",
  },
  {
    id: 4,
    imageSrc: require("../../public/images/themarketmood.png"),
    title: "The Market Mood",
    description: "Worked on design and deployment for a stock report service.",
    githubLink: "https://themarketmood.com/",
    demoLink: "https://themarketmood.com/",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Work",
    involvement: "Design to Deployment",
  },
  {
    id: 5,
    imageSrc: require("../../public/images/wewashh.png"),
    title: "We Washh",
    description:
      "Focused on development and deployment with minor design contributions for a laundry service.",
    githubLink: "https://www.wewashh.com/",
    demoLink: "https://www.wewashh.com/",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Work",
    involvement: "Development to Deployment",
  },
  {
    id: 6,
    imageSrc: require("../../public/images/011grpl.png"),
    title: "011GRPL",
    description:
      "Worked on design and deployment for a Brazilian Jiu-Jitsu training platform.",
    githubLink: "https://011grpl.com/home.html",
    demoLink: "https://011grpl.com/home.html",
    techStack: ["HTML", "CSS", "Bootstrap"],
    type: "Work",
    involvement: "Design to Deployment",
  },
];
